### ISSUE TITLE
Consider using a newer version of buildifier

### ISSUE THREAD

**Issue by seh** [thompsonja/bazel-buildifier#2]
At present this action [uses _buildifier_ version 3.0.0](https://github.com/thompsonja/bazel-buildifier/blob/ed40740aaf771bbcdd9b71bb5d4e64ae45c5cf4d/Dockerfile#L3). As of this writing, _buildifier_ is now available at [version 4.0.1](https://github.com/bazelbuild/buildtools/releases/tag/4.0.1). Can we update the _Dockerfile_ to use this newer version?

Thank you for this action. It's more convenient than [integrating _buildifier_ into our Bazel configuration](https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md#setup-and-usage-via-bazel), which has resulted in numerous intractable conflicts.

**Comment by thompsonja** [comment]
Sounds good, if you use v0.3.0 of this action (See #3), it will use buildifier 4.0.1. At some point I will make the buildifier version be an arg to the action itself.

**Comment by seh** [comment]
Thank you for the fast update!

**Comment by seh** [comment]
See #4 for a follow-on request.
