### ISSUE TITLE
Consider using a newer version of buildifier (again)

### ISSUE THREAD

**Issue by seh** [thompsonja/bazel-buildifier#4]
At present this action [uses _buildifier_ version 4.0.1](https://github.com/thompsonja/bazel-buildifier/blob/46d8f5ee2806d03ad95ba6e471af4ae4e04a451a/Dockerfile#L3). As of this writing, _buildifier_ is now available at [version 4.2.5](https://github.com/bazelbuild/buildtools/releases/tag/4.2.5). Can we update the _Dockerfile_ to use this newer version?

In https://github.com/thompsonja/bazel-buildifier/issues/2#issuecomment-819699432 we had considered introducing a parameter for the action to select the _buildifier_ version.

**Comment by thompsonja** [comment]
The v0.4.0 release adds the ability to specify the buildifier version.
